######################################################################
# Automatically generated by qmake (3.0) Wed Jun 21 13:05:24 2017
######################################################################

TEMPLATE = app
TARGET = ugrid-gui
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += ultragrid_window.hpp
FORMS += ultragrid_window.ui
SOURCES += ultragrid_window.cpp \
	main.cpp
